<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Dsh.Core\Dsh.Core.csproj" />
    <ProjectReference Include="..\Dsh.Plugins.Host\Dsh.Plugins.Host.csproj" />
    <ProjectReference Include="..\Dsh.Plugins.Native\Dsh.Plugins.Native.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
