namespace Dsh.Plugins.Generator;

public sealed partial class DshPluginCatalogGenerator
{
    private static class Templates
    {
        public const string Header = """
            // <auto-generated />
            #nullable enable
            using System;
            using System.Collections.Generic;
            using System.Diagnostics.CodeAnalysis;

            namespace Dsh.Plugins.Generated
            {
                public sealed class PluginEntry
                {
                    public PluginEntry(string package, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] Type implementation)
                    {
                        Package = package;
                        Implementation = implementation;
                    }

                    public string Package { get; }
                    [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)]
                    public Type Implementation { get; }
                }

                public static class DshPluginCatalog
                {
                    public static IReadOnlyList<PluginEntry> GetPlugins()
                    {
                        var list = new List<PluginEntry>({capacity});
            """;

        public const string EntryLine = """            list.Add(new PluginEntry("{package}", typeof({typeName})));""";

        public const string Footer = """
                        return list;
                    }

                    static DshPluginCatalog()
                    {
                        foreach (var entry in GetPlugins())
                            Dsh.Plugins.DshPluginCatalogRegistry.Register(entry.Package, entry.Implementation);
                    }
                }
            }

            namespace Dsh.Launcher
            {
                public static class PluginRoot
                {
                    public static void EnsureRooted()
                    {
                        _ = Dsh.Plugins.Generated.DshPluginCatalog.GetPlugins();
                    }
                }
            }
            """;
    }
}
